- name: deploy
  hosts: all
  become: yes

  tasks:

    - name: Add Jordy's GitHub key
      ansible.posix.authorized_key:
        user: vagrant
        state: present
        key: "{{ lookup('url', 'https://github.com/jofeltje2.keys', split_lines=False) }}"

    - name: Add Ana's GitHub key
      ansible.posix.authorized_key:
        user: vagrant
        state: present
        key: "{{ lookup('url', 'https://github.com/anaterna.keys', split_lines=False) }}"

    - name: Add Marina's GitHub key
      ansible.posix.authorized_key:
        user: vagrant
        state: present
        key: "{{ lookup('url', 'https://github.com/mescribano23.keys', split_lines=False) }}"

    - name: Add Matteo's GitHub key
      ansible.posix.authorized_key:
        user: vagrant
        state: present
        key: "{{ lookup('url', 'https://github.com/mfregonara.keys', split_lines=False) }}"

    - name: Add Monica's GitHub key
      ansible.posix.authorized_key:
        user: vagrant
        state: present
        key: "{{ lookup('url', 'https://github.com/monica-paun.keys', split_lines=False) }}"

    - name: disable swap
      ansible.builtin.shell:
        cmd: swapoff -a

    - name: remove swap
      ansible.builtin.lineinfile:
        path: /etc/fstab
        regexp: '^/swap.img'
        state: absent

    - name: br_netfilter_k8s_conf
      ansible.builtin.shell:
        cmd: touch /etc/modules-load.d/k8s.conf

    - name: br_netfilter_copy_module_overlay
      ansible.builtin.shell:
        cmd: echo 'overlay' > /etc/modules-load.d/k8s.conf

    - name: br_netfilter_copy_modules_br_netfilter
      ansible.builtin.shell:
        cmd: echo 'br_netfilter' > /etc/modules-load.d/k8s.conf

    - name: load module br_netfilter
      ansible.builtin.shell:
        cmd: modprobe br_netfilter

    - name: load module overlay
      ansible.builtin.shell:
        cmd: modprobe overlay






    




        

