apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: app-service-monitor
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: app
  endpoints:
    - port: http
      path: /api/v1/metrics
      interval: 15s
