apiVersion: monitoring.coreos.com/v1
kind: Alertmanager
metadata:
  name: {{ .Release.Name }}-alertmanager
  namespace: monitoring
spec:
  image: quay.io/prometheus/alertmanager:v0.24.0
  replicas: 1
  version: v0.24.0