apiVersion: apps/v1
kind: Deployment
metadata:
  name: model-service
spec:
  replicas: {{ .Values.model.replicas | default 1 }}
  selector:
    matchLabels:
      app: model-service
  template:
    metadata:
      labels:
        app: model-service
    spec:
      containers:
        - name: model-service
          image: {{ .Values.model.image.repository }}:{{ .Values.model.image.tag }}
          imagePullPolicy: {{ .Values.model.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.backendService.port }}
          envFrom:
            - configMapRef:
                name: model-service-config
            - secretRef:
                name: {{ .Release.Name }}-secret
          volumeMounts:
            - name: shared-volume
              mountPath: /app/shared
      volumes:
        - name: shared-volume
          emptyDir: {}
            
---
apiVersion: v1
kind: Service
metadata:
  name: model-service
spec:
  selector:
    app: model-service
  ports:
    - port: {{ .Values.backendService.port }}
      targetPort: {{ .Values.backendService.port }}
  type: {{ .Values.service.type }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: model-service-config
data:
  MODEL_SERVICE_VERSION: "{{ .Values.model.version }}"
  MODEL_URL: "{{ .Values.model.modelUrl }}"
  MODEL_PATH: "{{ .Values.model.modelPath }}"
  BOW_URL: "{{ .Values.model.bowUrl }}"
  BOW_PATH: "{{ .Values.model.bowPath }}"
  PORT: "{{ .Values.backendService.port }}"
  HOST: "{{ .Values.backendService.host }}"