apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-model-service-v1
  labels: 
    app: {{ .Release.Name }}-model-service
    version: v1 
spec:
  replicas: {{ .Values.model.replicas | default 1 }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-model-service
      version: v1
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-model-service
        version: v1
    spec:
      containers:
        - name: {{ .Release.Name }}-model-service
          image: {{ .Values.model.image.repository }}:{{ .Values.model.image.tag1 }}
          imagePullPolicy: {{ .Values.model.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.backendService.port }}
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-model-service-config
            - secretRef:
                name: {{ .Release.Name }}-secret
          volumeMounts:
            - name: shared-volume
              mountPath: /mnt/shared
      volumes:
        - name: shared-volume
          {{- if .Values.volume.enabled }}
          hostPath:
            path: {{ .Values.volume.hostPath }}
          {{- else }}
          emptyDir: {}
          {{- end }}
            
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-model-service-v2
  labels: 
    app: {{ .Release.Name }}-model-service
    version: v2
spec:
  replicas: {{ .Values.model.replicas | default 1 }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-model-service
      version: v2
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-model-service
        version: v2
    spec:
      containers:
        - name: {{ .Release.Name }}-model-service
          image: {{ .Values.model.image.repository }}:{{ .Values.model.image.tag2 }}
          imagePullPolicy: {{ .Values.model.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.backendService.port }}
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-model-service-config
            - secretRef:
                name: {{ .Release.Name }}-secret
          volumeMounts:
            - name: shared-volume
              mountPath: /mnt/shared
      volumes:
        - name: shared-volume
          {{- if .Values.volume.enabled }}
          hostPath:
            path: {{ .Values.volume.hostPath }}
          {{- else }}
          emptyDir: {}
          {{- end }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-model-service
spec:
  selector:
    app: {{ .Release.Name }}-model-service
  ports:
    - port: 80
      targetPort: {{ .Values.backendService.port }}
  type: {{ .Values.service.type }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-model-service-config
data:
  MODEL_SERVICE_VERSION: "{{ .Values.model.version }}"
  MODEL_URL: "{{ .Values.model.modelUrl }}"
  MODEL_PATH: "{{ .Values.model.modelPath }}"
  BOW_URL: "{{ .Values.model.bowUrl }}"
  BOW_PATH: "{{ .Values.model.bowPath }}"
  PORT: "{{ .Values.backendService.port }}"
  HOST: "{{ .Values.backendService.host }}"