- name: deploy
  hosts: ctrl
  become: yes

  tasks:
    - name: Check if kubeadm has already initialized the cluster
        ansible.builtin.stat:
          path: /etc/kubernetes/admin.conf
        register: kubeadm_config

      - name: Initialize the Kubernetes cluster
        ansible.builtin.command: >
          kubeadm init
          --apiserver-advertise-address=192.168.56.100
          --node-name ctrl
          --pod-network-cidr=10.244.0.0/16
        when: not kubeadm_config.stat.exists

      - name: Ensure .kube directory exists for vagrant user
        ansible.builtin.file:
          path: /home/vagrant/.kube
          state: directory
          owner: vagrant
          group: vagrant
          mode: '0755'

      - name: Copy admin.conf to vagrant's kube config
        ansible.builtin.copy:
          src: /etc/kubernetes/admin.conf
          dest: /home/vagrant/.kube/config
          remote_src: yes
          owner: vagrant
          group: vagrant
          mode: '0644'
        when: kubeadm_config.stat.exists

      - name: Copy admin.conf to shared folder for host access
        ansible.builtin.copy:
          src: /etc/kubernetes/admin.conf
          dest: /vagrant/admin.conf
          remote_src: yes
          owner: vagrant
          group: vagrant
          mode: '0644'

      - name: Download Flannel network manifest
        ansible.builtin.get_url:
          url: https://raw.githubusercontent.com/flannel-io/flannel/v0.26.7/examples/kube-flannel.yml
          dest: /home/vagrant/kube-flannel.yml
          mode: '0644'
          owner: vagrant
          group: vagrant

      - name: Patch Flannel to use eth1
        ansible.builtin.replace:
          path: /home/vagrant/kube-flannel.yml
          regexp: '--kube-subnet-mgr'
          replace: '--kube-subnet-mgr\n            - --iface=eth1'

      - name: Apply Flannel manifest
        become_user: vagrant
        ansible.builtin.command: kubectl apply -f /home/vagrant/kube-flannel.yml
        environment:
          KUBECONFIG: /home/vagrant/.kube/config

      - name: Add Helm GPG Ubuntu/Debian signing key
        ansible.builtin.apt_key:
          url: https://baltocdn.com/helm/signing.asc
          state: present

      - name: Add Helm apt repository
        ansible.builtin.apt_repository:
          repo: "deb https://baltocdn.com/helm/stable/debian/ all main"
          state: present

      - name: Update apt cache for Helm
        ansible.builtin.apt:
          update_cache: yes

      - name: Install Helm
        ansible.builtin.apt:
          name: helm
          state: present

      - name: Install helm-diff plugin
        become_user: vagrant
        ansible.builtin.command: helm plugin install https://github.com/databus23/helm-diff
        environment:
          HOME: /home/vagrant
        args:
          creates: /home/vagrant/.local/share/helm/plugins/helm-diff



        

