apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  components:
    ingressGateways:
      - name: istio-ingressgateway
        enabled: true
        k8s:
          service: 
            type: LoadBalancer
            loadBalancerIP: 192.168.56.91
