- name: deploy
  hosts: workers
  become: yes

  tasks:
    - name: Ensure kubelet is started and enabled
      ansible.builtin.systemd:
        name: kubelet
        state: started
        enabled: yes

    # Step 18. Generate join command for setting up k8s workers
    - name: Generate join command
      ansible.builtin.command: >
        kubeadm token create
        --print-join-command
      delegate_to: ctrl
      run_once: true
      register: join_command

    - name: Print join command
      debug:
        var: join_command.stdout

    # Step 19. Run join command
    - name: Run join command
      ansible.builtin.shell: "{{ join_command.stdout }} --ignore-preflight-errors=all"
      args:
        creates: /etc/kubernetes/kubelet.conf
